{ config, pkgs, ... }:
let
  certDomain = "cert.home.arpa";
in
{
  services.caddy = {
    enable = true;
    globalConfig = ''
      local_certs
      metrics {
        per_host
      }
    '';
    virtualHosts."${certDomain}:80".extraConfig = ''
      file_server {
        root ${config.services.caddy.dataDir}/.local/share/caddy/pki/authorities/local
      }
      rewrite * root.crt
      header Content-Disposition "attachment; filename=root.crt"
    '';
    virtualHosts."${certDomain}:443".extraConfig = "redir http://${certDomain}";
    virtualHosts."ha.home.arpa".extraConfig = "reverse_proxy 192.168.0.10:80";
  };
  users.users."${config.services.caddy.user}".packages = with pkgs; [
    nss
    nss.tools
  ];
  networking.firewall.allowedTCPPorts = [
    80
    443
  ];
  services.borgmatic.configurations.mantis.source_directories = [ config.services.caddy.dataDir ];
  security.pki.certificates = [
    # This is the certificate generated by Caddy, but manually added here
    # because the certificate file wouldn't be available if this was set up
    # on a fresh machine.
    # Obviosly, a fresh machine would generate another certificate, so this
    # needs to changed after that, but it wouldn't cause an error on build.
    # Self-trusting is necessary for OIDC.
    ''
      -----BEGIN CERTIFICATE-----
      MIIBpDCCAUmgAwIBAgIQVcHk0EAV4ScnoE0USOGjITAKBggqhkjOPQQDAjAwMS4w
      LAYDVQQDEyVDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSAyMDI1IEVDQyBSb290MB4X
      DTI1MDYxMDIyNTg0OFoXDTM1MDQxOTIyNTg0OFowMDEuMCwGA1UEAxMlQ2FkZHkg
      TG9jYWwgQXV0aG9yaXR5IC0gMjAyNSBFQ0MgUm9vdDBZMBMGByqGSM49AgEGCCqG
      SM49AwEHA0IABKtrAkiIIMGpHkM2PjAEBTz5sd1TIYrppUFD50JWpfb5Vj2/mf9m
      Zm5TduWJRXB8PER+OggzqlfoLA3jP+jNN+ejRTBDMA4GA1UdDwEB/wQEAwIBBjAS
      BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTtAGw9phroreYkaRk7ot1fMZnr
      xDAKBggqhkjOPQQDAgNJADBGAiEA2ecT57GxPbwHEy0aASv2HiBJRu4wj7nLmk1j
      5odD8F4CIQCEJUdwALVVoR9wefcT/mhdRqy5krKI86Q7LgPH8swpOA==
      -----END CERTIFICATE-----
    ''
  ];
}
