# Current self-signed cert authority
builtins.toFile "cert.crt" ''
  -----BEGIN CERTIFICATE-----
  MIIBpDCCAUmgAwIBAgIQVcHk0EAV4ScnoE0USOGjITAKBggqhkjOPQQDAjAwMS4w
  LAYDVQQDEyVDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSAyMDI1IEVDQyBSb290MB4X
  DTI1MDYxMDIyNTg0OFoXDTM1MDQxOTIyNTg0OFowMDEuMCwGA1UEAxMlQ2FkZHkg
  TG9jYWwgQXV0aG9yaXR5IC0gMjAyNSBFQ0MgUm9vdDBZMBMGByqGSM49AgEGCCqG
  SM49AwEHA0IABKtrAkiIIMGpHkM2PjAEBTz5sd1TIYrppUFD50JWpfb5Vj2/mf9m
  Zm5TduWJRXB8PER+OggzqlfoLA3jP+jNN+ejRTBDMA4GA1UdDwEB/wQEAwIBBjAS
  BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBTtAGw9phroreYkaRk7ot1fMZnr
  xDAKBggqhkjOPQQDAgNJADBGAiEA2ecT57GxPbwHEy0aASv2HiBJRu4wj7nLmk1j
  5odD8F4CIQCEJUdwALVVoR9wefcT/mhdRqy5krKI86Q7LgPH8swpOA==
  -----END CERTIFICATE-----
''
